config/routes.rb
Rails.application.routes.draw do
  resources :medicines
  resources :doctors do
    resources :prescriptions do
      # get 'presc_medicines/new', to: 'presc_medicines#new', as: 'new_presc_medicines'
      # post 'presc_medicines', to: 'presc_medicines#create'
      # get 'presc_medicines/:id/edit', to: 'presc_medicines#edit', as: 'edit_presc_medicines'
      # patch 'presc_medicines/:id', to: 'presc_medicines#update'
      # delete 'presc_medicines/:id', to: 'presc_medicines#destroy'
    end
  end
  get 'prescriptions', to: 'prescriptions#all_index', as: 'prescriptions'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  has_many :presc_medicines
  has_many :prescriptions, through: :presc_medicines
  validates :meds_name, presence: true
  validates :meds_cost, presence: true, numericality: true
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: %i[show edit update destroy]

  def index
    @q = Medicine.ransack(params[:q])
    @medicines = @q.result(distinct: true)
  end

  def show; end

  def new
    @medicine = Medicine.new
  end

  def edit; end

  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to medicine_url(@medicine), notice: 'Medicine was successfully created.' }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to medicine_url(@medicine), notice: 'Medicine was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @medicine.destroy

    respond_to do |format|
      format.html { redirect_to medicines_url, notice: 'Medicine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_medicine
    @medicine = Medicine.find(params[:id])
  end

  def medicine_params
    params.require(:medicine).permit(:meds_name, :meds_cost, :meds_category)
  end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
<%= form_with model: medicine, class: 'row g-2' do |form| %>
	<% if medicine.errors.any? %>
		<div class="alert alert-danger" role="alert" id="error_explanation">
			<h4 class='alert-heading'><%= pluralize(medicine.errors.count, "error") %> prohibited this medicine from being saved:</h4>
			<hr>
			<ul>
				<% medicine.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field form-floating mb-3">
		<%= form.text_field :meds_name, class: 'form-control form-control-lg', placeholder: 'Medicine name' %>
		<%= form.label :meds_name, 'Medicine Name', class: 'form-label' %>
	</div>
	<div class="field form-floating mb-3 col-md-8">
		<%= form.text_field :meds_category, class: 'form-control form-control-lg', placeholder: 'Medicine Category' %>
		<%= form.label :meds_category, 'Category', class: 'form-label'  %>
	</div>
	<div class="field form-floating mb-3 col-md-4">
		<%= form.number_field :meds_cost, class: 'form-control form-control-lg', placeholder: 'Cost in PHP' %>
		<%= form.label :meds_cost, 'Cost', class: 'form-label'  %>
	</div>
	<div class="actions">
		<%= form.submit 'Submit', class: 'btn btn-outline-success' %>
		<%= link_to 'Cancel', medicines_path, class: 'btn btn-outline-danger' %>
	</div>
<% end %>

app/views/medicines/_search_form.html.erb
<%= search_form_for @q do |f| %>
	<div class='row align-items-center mb-3'>
		<div class="col-4">
			<%= f.search_field :meds_name_or_meds_category_cont, class: 'form-control', placeholder: 'Search by Medicine Name or Category' %>
		</div>
		<div class="col-auto">
			<%= f.submit 'Search', class: 'btn btn-outline-info' %>
		</div>
	</div>
<% end %>

app/views/medicines/edit.html.erb
<div class="row justify-content-center">
	<div class="col-8">
		<h4 class='mb-4'>Update Medicine Details</h4>
		<%= render 'form', medicine: @medicine %>
	</div>
</div>

app/views/medicines/index.html.erb
<%= render 'search_form' %>
<table class='table table-striped border'>
	<caption>List of Medicines</caption>
	<thead class='bg-primary'>
		<tr class='heading-color'>
			<th>
				<%= sort_link(@q, :meds_name) do %>
					<strong class='text-white'>Name</strong>
				<% end %>
			</th>
			<th>
				<%= sort_link(@q, :meds_cost) do %>
					<strong class='text-white'>Cost (Php)</strong>
				<% end %>
			</th>
			<th>
				<%= sort_link(@q, :meds_category) do %>
					<strong class='text-white'>Category</strong>
				<% end %>
			</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @medicines.each do |medicine| %>
			<tr>
				<td><%= link_to "#{medicine.meds_name}", medicine, class: 'table-link' %></td>
				<td><%= medicine.meds_cost %></td>
				<td><%= medicine.meds_category %></td>
				<td>
					<div class="btn-group" role="group" aria-label="Basic outlined example">
						<%= link_to 'Edit', edit_medicine_path(medicine), class: 'btn btn-outline-primary' %>
						<%= link_to 'Delete', medicine, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-primary' %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Add New Medicine', new_medicine_path, class: 'btn btn-outline-success'  %>

app/views/medicines/new.html.erb
<div class="row justify-content-center">
	<div class="col-8">
		<h4 class='mb-4'>Register New Medicine</h4>
		<%= render 'form', medicine: @medicine %>
	</div>
</div>

app/views/medicines/show.html.erb
<div class="row justify-content-center">
	<div class="mt-4 p-5 bg-primary text-white rounded col-8">
		<h1>
			<%= @medicine.meds_name %>
		</h1>
		<div class='mb-3'>
			<strong>Category:</strong>
			<span>
				<%= @medicine.meds_category %>
			</span>
			| 
			<strong>Cost:</strong>
			<span>
				Php <%= @medicine.meds_cost %>
			</span>
		</div>
		<p>
			<%= link_to 'Edit', edit_medicine_path(@medicine), class: 'btn btn-outline-light text-white me-1' %>
			<%= link_to 'Back', medicines_path, class: 'btn btn-outline-light text-white' %>
		</p>
	</div>
</div>