config/routes.rb
Rails.application.routes.draw do
  resources :medicines
  resources :doctors do
    resources :prescriptions do
      # get 'presc_medicines/new', to: 'presc_medicines#new', as: 'new_presc_medicines'
      # post 'presc_medicines', to: 'presc_medicines#create'
      # get 'presc_medicines/:id/edit', to: 'presc_medicines#edit', as: 'edit_presc_medicines'
      # patch 'presc_medicines/:id', to: 'presc_medicines#update'
      # delete 'presc_medicines/:id', to: 'presc_medicines#destroy'
    end
  end
  get 'prescriptions', to: 'prescriptions#all_index', as: 'prescriptions'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :doctor
  has_many :presc_medicines
  has_many :medicines, through: :presc_medicines
  accepts_nested_attributes_for :presc_medicines, allow_destroy: true, reject_if: :all_blank

  def total_cost
    total = 0
    presc_medicines.each do |presc_meds|
      total += presc_meds.discounted_price
    end

    total
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: %i[show edit update destroy]
  before_action :find_doctor, only: %i[index show new create edit update destroy]

  def index
    # @prescriptions = @doctor.prescriptions
    @q = @doctor.prescriptions.ransack(params[:q])
    @prescriptions = @q.result(distinct: true)
  end

  def all_index
    @q = Prescription.ransack(params[:q])
    @prescriptions = @q.result(distinct: true)
  end

  def show
    @presc_medicines = @prescription.presc_medicines
  end

  def new
    @prescription = @doctor.prescriptions.build
    # Used to add a prescribed medicine field
    @prescription.presc_medicines.build
  end

  def edit; end

  def create
    @prescription = @doctor.prescriptions.build(prescription_params)

    respond_to do |format|
      if @prescription.save
        format.html do
          redirect_to doctor_prescriptions_path(@doctor), notice: 'Prescription was successfully created.'
        end
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescriptions/1 or /prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html do
          redirect_to doctor_prescriptions_path(@doctor), notice: 'Prescription was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @prescription.presc_medicines.find_each(&:destroy)
    @prescription.destroy

    respond_to do |format|
      format.html { redirect_to doctor_prescriptions_path(@doctor), notice: 'Prescription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end

  def set_prescription
    @prescription = Prescription.find(params[:id])
  end

  def prescription_params
    params.require(:prescription).permit(:doctor_id, :title, :description, :prescribed_date,
                                         presc_medicines_attributes: %i[id prescription_id medicine_id quantity discount _destroy])
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
  def grouped_medicine_options
    Medicine.all.map do |m|
      [m.meds_category, "#{m.meds_name} - Php #{m.meds_cost}", m.id, { 'data-cost': m.meds_cost }]
    end.group_by(&:shift)
  end
end

app/views/prescriptions/_form.html.erb
<%= form_with model: [@doctor, @prescription], class: 'row g-2' do |form| %>
	<% if prescription.errors.any? %>
		<div class="alert alert-danger" role="alert" id="error_explanation">
			<h4 class='alert-heading'><%= pluralize(prescription.errors.count, "error") %> prohibited this prescription from being saved:</h4>
			<hr>
			<ul>
				<% prescription.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field form-floating mb-3">
		<%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
		<%= form.label :title, 'Title' %>
	</div>
	<div class="field form-floating mb-3">
		<%= form.text_field :description, class: 'form-control', placeholder: 'Description' %>
		<%= form.label :description, 'Description' %>
	</div>
	<div class='mb-3 col-auto row'>
		<div class="col-auto d-flex align-items-center">
			<%= form.label :prescribed_date, 'Prescribed Date:', class: 'col-auto' %>
			<%= form.date_select :prescribed_date, {}, {class: 'form-select ms-2'}%>
		</div>
	</div>
	<div class="row mb-3">
		<p>
			<span class='col-sm-2'>Total Cost: Php</span>
			<span class='total_cost col-sm-2'></span>
		</p>
	</div>
	<div class="field">
		<%= form.number_field :doctor_id, type: :hidden %>
	</div>
	<fieldset>
		<legend>Medicine:</legend>
		<%= link_to_add_fields "Add Medicine", form, :presc_medicines %>
		<%= form.fields_for :presc_medicines do |presc_meds_form| %>
			<%= render "presc_medicine_fields", f: presc_meds_form %>
		<% end %>
	</fieldset>
	<div class="actions">
		<%= form.submit 'Submit', class: 'btn btn-outline-success' %>
		<%= link_to 'Cancel', doctor_prescriptions_path, class: 'btn btn-outline-danger' %>
	</div>
<% end %>

app/views/prescriptions/_presc_medicine_fields.html.erb
<div class="nested-fields">
	<%= f.hidden_field :_destroy %>
	<div class='presc_meds_fields'>
		<div>
			<%= f.number_field :prescription_id, type: :hidden %>
		</div>
		<div class='row align-items-center mb-3'>
			<div class='form-floating col-auto'>
				<%= f.select :medicine_id, grouped_medicine_options, {}, {class: 'input_meds form-select'}%>
				<%= f.label :medicine_id, 'Prescribed Medicine', class: 'ms-1' %>
			</div>
			<div class="form-floating col-2">
				<%= f.number_field :quantity, class: 'quantity_fields form-control', placeholder: 'Quantity' %>
				<%= f.label :quantity, 'Quantity', class: 'ms-1' %>
			</div>
			<div class='discount-container col-auto d-flex align-items-center'>
				<div class='form-floating col-3 me-3'>
					<input id='discount-output' class='discount_output form-control' type='number' min='0' max='100'>
					<label for="discount-output">Discount (%)</label>
				</div>
				<%= f.range_field :discount, in: 0..100, class: 'discount_fields form-range' %>
			</div>
			<div class='col-auto'>
				<%= link_to "Remove", '#', class: "remove_fields btn btn-outline-danger" %>
			</div>
		</div>
	</div>
</div>

app/views/prescriptions/_search_form.html.erb
<%= search_form_for @q do |f| %>
	<div class='row align-items-center mb-3'>
		<div class="col-4">
			<%= f.search_field :presc_medicines_medicine_id_cont, class: 'form-control', placeholder: 'Search by Medicine Name or Category' %>
		</div>
		<div class="col-auto">
			<%= f.submit 'Search', class: 'btn btn-outline-info' %>
		</div>
	</div>
<% end %>

app/views/prescriptions/all_index.html.erb
<table class='table table-striped border'>
	<caption>List of Prescriptions</caption>
	<thead class='bg-primary'>
		<tr class='heading-color'>
			<th>
				<%= sort_link(@q, :title) do %>
					<strong class='text-white'>Title</strong>
				<% end %>
			</th>
			<th>Description</th>
			<th>
				<%= sort_link(@q, :total_cost) do %>
					<strong class='text-white'>Total Cost (Php)</strong>
				<% end %>
			</th>
			<th>Prescribed Medicines</th>
			<th>
				<%= sort_link(@q, :prescribed_date) do %>
					<strong class='text-white'>Prescribed Date</strong>
				<% end %>
			</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @prescriptions.each do |prescription| %>
			<tr>
				<td><%= link_to "#{prescription.title}", doctor_prescription_path(prescription.doctor_id, prescription), class: 'table-link' %></td>
				<td><%= prescription.description %></td>
				<td><%= prescription.total_cost %></td>
				<td>
					<ul>
						<% prescription.presc_medicines.each do |presc_medicine| %>
							<li>
								<%= presc_medicine.medicine.meds_name%>
								<span> - </span>
								<%= presc_medicine.quantity%>
							</li>
						<% end %>
					</ul>
				</td>
				<td>
					<%= prescription.prescribed_date %>
				</td>
				<td>
					<div class="btn-group" role="group" aria-label="Basic outlined example">
						<%= link_to 'Edit', edit_doctor_prescription_path(prescription.doctor_id, prescription), class: 'btn btn-outline-primary' %>
						<%= link_to 'Delete', doctor_prescription_path(prescription.doctor_id, prescription), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-primary' %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/prescriptions/edit.html.erb
<div class="row justify-content-center">
	<div class="col-10">
		<h4 class='mb-4'>Update Prescription Details</h4>
		<%= render 'form', prescription: @prescription %>
	</div>
</div>

app/views/prescriptions/index.html.erb
<table class='table table-striped border'>
	<caption>List of Doctor <%= @doctor.doctor_name%>'s Prescriptions</caption>
	<thead class='bg-primary'>
		<tr class='heading-color'>
			<th>
				<%= sort_link(@q, :title) do %>
					<strong class='text-white'>Title</strong>
				<% end %>
			</th>
			<th>Description</th>
			<th>
				<%= sort_link(@q, :total_cost) do %>
					<strong class='text-white'>Total Cost (Php)</strong>
				<% end %>
			</th>
			<th>Prescribed Medicines</th>
			<th>
				<%= sort_link(@q, :prescribed_date) do %>
					<strong class='text-white'>Prescribed Date</strong>
				<% end %>
			</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @prescriptions.each do |prescription| %>
			<tr>
				<td><%= link_to "#{prescription.title}", doctor_prescription_path(@doctor, prescription), class: 'table-link' %></td>
				<td><%= prescription.description %></td>
				<td><%= prescription.total_cost %></td>
				<td>
					<ul>
						<% prescription.presc_medicines.each do |presc_medicine| %>
							<li>
								<%= presc_medicine.medicine.meds_name%>
								<span> - </span>
								<%= presc_medicine.quantity%>
							</li>
						<% end %>
					</ul>
				</td>
				<td>
					<%= prescription.prescribed_date %>
				</td>
				<td>
					<div class="btn-group" role="group" aria-label="Basic outlined example">
						<%= link_to 'Edit', edit_doctor_prescription_path(@doctor, prescription), class: 'btn btn-outline-primary' %>
						<%= link_to 'Delete', doctor_prescription_path(@doctor, prescription), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-primary' %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Add New Prescription', new_doctor_prescription_path, class: 'btn btn-outline-success' %>

app/views/prescriptions/new.html.erb
<div class="row justify-content-center">
	<div class="col-10">
		<h4 class='mb-4'>Register New Prescription</h4>
		<%= render 'form', prescription: @prescription %>
	</div>
</div>

app/views/prescriptions/show.html.erb
<div class="row justify-content-center">
	<%= @test%>
	<div class="mt-4 p-5 bg-primary text-white rounded col-8">
		<h1>
			<%= @prescription.title %>
		</h1>
		<div class='mb-3'>
			<p>
				<%= @prescription.description %>
			</p>
			<strong>Total Cost:</strong>
			<span>
				<%= @prescription.total_cost %>
			</span>
		</div>
		<div>
			<strong>Prescribed Medcicines:</strong>
			<% @presc_medicines.each do |presc_medicine| %>
				<p class='mt-1 ms-3'>
					<%= presc_medicine.quantity%>
					<%= presc_medicine.medicine.meds_name%>
					<span> - </span>
					Php <%= presc_medicine.discounted_price%>
				</p>
			<% end %>
		</div>
		<p>
			<%= link_to 'Edit', edit_doctor_prescription_path(@doctor, @prescription), class: 'btn btn-outline-light text-white me-1' %>
			<%= link_to 'Back', doctor_prescriptions_path, class: 'btn btn-outline-light text-white' %>
		</p>
	</div>
</div>