config/routes.rb
Rails.application.routes.draw do
  resources :medicines
  resources :doctors do
    resources :prescriptions do
      # get 'presc_medicines/new', to: 'presc_medicines#new', as: 'new_presc_medicines'
      # post 'presc_medicines', to: 'presc_medicines#create'
      # get 'presc_medicines/:id/edit', to: 'presc_medicines#edit', as: 'edit_presc_medicines'
      # patch 'presc_medicines/:id', to: 'presc_medicines#update'
      # delete 'presc_medicines/:id', to: 'presc_medicines#destroy'
    end
  end
  get 'prescriptions', to: 'prescriptions#all_index', as: 'prescriptions'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @prescriptions = Prescription.limit(9)
    @medicines = Medicine.limit(9)
    @doctors = Doctor.limit(9)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-secondary'>
	<div class="container-fluid">
		<%= link_to 'Prescription Tracker App', root_path, class: 'navbar-brand link-color'%>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
			<div class="navbar-nav">
				<%= link_to 'Doctors', doctors_path, class: 'nav-link link-color'%>
				<%= link_to 'Medicines', medicines_path, class: 'nav-link link-color'%>
				<%= link_to 'Prescriptions', prescriptions_path, class: 'nav-link link-color'%>
			</div>
		</div>
	</div>
</nav>

app/views/home/index.html.erb
<div class="row">
	<h4>Prescriptions</h4>
	<% @prescriptions.each do |prescription| %>
		<div class="col-auto mb-3">
			<div class="card overlow-auto">
				<div class="card-body">
					<h5 class="card-title">
						<%= prescription.title %>
					</h5>
					<p class="card-text">
						<%= prescription.description %>
						<ul>
							<% prescription.presc_medicines.each do |presc_medicine| %>
								<li>
									<%= presc_medicine.medicine.meds_name%>
									<span> - </span>
									<%= presc_medicine.quantity%>
								</li>
							<% end %>
						</ul>
						<strong>Total Cost: </strong>Php 
						<%= prescription.total_cost %>
					</p>
				</div>
				<div class="card-footer bg-tertiary">
					<%= link_to 'See Prescription', doctor_prescription_path(prescription.doctor_id, prescription), class: 'btn btn-outline-primary' %>
				</div>
			</div>
		</div>
	<% end %>
	<div class="col-auto align-self-center">
		<%= link_to 'See All Prescriptions', prescriptions_path, class: 'btn btn-outline-primary'%>
	</div>
</div>
<div class="row">
	<h4>Medicines</h4>
	<% @medicines.each do |medicine| %>
		<div class="col-auto mb-3">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">
						<%= medicine.meds_name %>
					</h5>
					<p class="card-text">
						<%= medicine.meds_category %> -
						Php <%= medicine.meds_cost %>
					</p>
				</div>
			</div>
			<div class="card-footer bg-tertiary">
				<%= link_to 'See Medicine', medicine, class: 'btn btn-outline-primary' %>
			</div>
		</div>
	<% end %>
	<div class="col-auto align-self-center">
		<%= link_to 'See All Medicines', medicines_path, class: 'btn btn-outline-primary'%>
	</div>
</div>
<div class="row">
	<h4>Doctors</h4>
	<% @doctors.each do |doctor| %>
		<div class="col-auto mb-3">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">
						<%= doctor.doctor_name %>
					</h5>
					<p class="card-text">
						<strong>Specialization:</strong>
						<span>
							<%= doctor.specialization %>
						</span>
					</p>
					<p class="card-text">
						<strong>Contact Number:</strong>
						<span>
							<%= doctor.doctor_phone %>
						</span>
					</p>
					<p class="card-text">
						<strong>Hospital:</strong>
						<span>
							<%= doctor.hospital %>
						</span>
					</p>
				</div>
			</div>
			<div class="card-footer bg-tertiary">
				<td><%= link_to 'See Doctor', doctor, class: 'btn btn-outline-primary' %></td>
			</div>
		</div>
	<% end %>
	<div class="col-auto align-self-center">
		<%= link_to 'See All Doctors', doctors_path, class: 'btn btn-outline-primary'%>
	</div>
</div>