config/routes.rb
Rails.application.routes.draw do
  resources :medicines
  resources :doctors do
    resources :prescriptions do
      # get 'presc_medicines/new', to: 'presc_medicines#new', as: 'new_presc_medicines'
      # post 'presc_medicines', to: 'presc_medicines#create'
      # get 'presc_medicines/:id/edit', to: 'presc_medicines#edit', as: 'edit_presc_medicines'
      # patch 'presc_medicines/:id', to: 'presc_medicines#update'
      # delete 'presc_medicines/:id', to: 'presc_medicines#destroy'
    end
  end
  get 'prescriptions', to: 'prescriptions#all_index', as: 'prescriptions'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :prescriptions
  validates :doctor_name, presence: true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[show edit update destroy]

  def index
    @q = Doctor.ransack(params[:q])
    @doctors = @q.result(distinct: true)
    # @doctors = Doctor.order(params[:sort])
  end

  def show; end

  def new
    @doctor = Doctor.new
  end

  def edit; end

  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctor_url(@doctor), notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:doctor_name, :doctor_phone, :specialization, :hospital)
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with model: doctor, class: 'row g-2' do |form| %>
	<% if doctor.errors.any? %>
		<div class="alert alert-danger" role="alert" id="error_explanation">
			<h4 class='alert-heading'><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h4>
			<hr>
			<ul>
				<% doctor.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field form-floating mb-3 col-12">
		<%= form.text_field :doctor_name, class: 'form-control', placeholder: 'Doctor Name' %>
		<%= form.label :doctor_name, "Doctor's Name", class: 'form-label'  %>
		<% if doctor.errors.full_messages_for(:doctor_name).any? %>
			<div class="alert-danger" role="alert" id="error_explanation">
				<% doctor.errors.full_messages_for(:doctor_name).each do |error| %>
					<p><%= error %></p>
				<% end %>
			</div>
		<% end %>
	</div>
	<div class="field form-floating mb-3  col-12">
		<%= form.text_field :doctor_phone, class: 'form-control', placeholder: 'Contact Number' %>
		<%= form.label :doctor_phone, 'Contact Number', class: 'form-label'  %>
	</div>
	<div class="field form-floating mb-3 col-md-6">
		<%= form.text_field :specialization, class: 'form-control', placeholder: 'Specialization' %>
		<%= form.label :specialization, 'Specialization', class: 'form-label'  %>
	</div>
	<div class="field form-floating mb-3 col-md-6">
		<%= form.text_field :hospital, class: 'form-control', placeholder: 'Hospital/Clinic' %>
		<%= form.label :hospital, 'Hospital/Clinic', class: 'form-label'  %>
	</div>
	<div class="actions">
		<%= form.submit 'Submit', class: 'btn btn-outline-success' %>
		<%= link_to 'Cancel', doctors_path, class: 'btn btn-outline-danger' %>
	</div>
<% end %>

app/views/doctors/_search_form.html.erb
<%= search_form_for @q do |f| %>
	<div class='row align-items-center mb-3'>
		<div class="col-4">
			<%= f.search_field :doctor_name_or_hospital_or_specialization_cont, class: 'form-control', placeholder: 'Search by Name, Specialization, or Hospital' %>
		</div>
		<div class="col-auto">
			<%= f.submit 'Search', class: 'btn btn-outline-info' %>
		</div>
	</div>
<% end %>

app/views/doctors/edit.html.erb
<div class="row justify-content-center">
	<div class="col-8">
		<h4 class='mb-4'>Update Doctor Details</h4>
		<%= render 'form', doctor: @doctor %>
	</div>
</div>

app/views/doctors/index.html.erb
<%= render 'search_form' %>
<table class='table table-striped border'>
	<caption>List of Doctors</caption>
	<thead class='bg-primary'>
		<tr class='heading-color'>
			<th>
				<%= sort_link(@q, :doctor_name) do %>
					<strong class='text-white'>Name</strong>
				<% end %>
			</th>
			<th>Contact Number</th>
			<th>
				<%= sort_link(@q, :specialization) do %>
					<strong class='text-white'>Specialization</strong>
				<% end %>
			</th>
			<th>
				<%= sort_link(@q, :hospital) do %>
					<strong class='text-white'>Hospital</strong>
				<% end %>
			</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @doctors.each do |doctor| %>
			<tr>
				<td><%= link_to "#{doctor.doctor_name}", doctor, class: 'table-link' %></td>
				<td><%= doctor.doctor_phone %></td>
				<td><%= doctor.specialization %></td>
				<td><%= doctor.hospital %></td>
				<td>
					<div class="btn-group" role="group" aria-label="Basic outlined example">
						<%= link_to 'See Prescriptions', doctor_prescriptions_path(doctor), class: 'btn btn-outline-primary' %>
						<%= link_to 'Edit', edit_doctor_path(doctor), class: 'btn btn-outline-primary' %>
						<%= link_to 'Delete', doctor, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-primary' %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Add New Doctor', new_doctor_path, class: 'btn btn-outline-success' %>

app/views/doctors/new.html.erb
<div class="row justify-content-center">
	<div class="col-8">
		<h4 class='mb-4'>Register New Doctor</h4>
		<%= render 'form', doctor: @doctor %>
	</div>
</div>

app/views/doctors/show.html.erb
<div class="row justify-content-center">
	<div class="mt-4 p-5 bg-primary text-white rounded col-8">
		<h1>
			<%= @doctor.doctor_name %>
		</h1>
		<div class='mb-3'>
			<strong>Specialization:</strong>
			<span>
				<%= @doctor.specialization %>
			</span>
			| 
			<strong>Contact Number:</strong>
			<span>
				<%= @doctor.doctor_phone %>
			</span>
			|
			<strong>Hospital:</strong>
			<span>
				<%= @doctor.hospital %>
			</span>
		</div>
		<p>
			<%= link_to 'Edit', edit_doctor_path(@doctor), class: 'btn btn-outline-light text-white me-1' %>
			<%= link_to 'Back', doctors_path, class: 'btn btn-outline-light text-white' %>
		</p>
	</div>
</div>